# fathalfath30 sdk database setup
# this docker compose is used to running database such asa Postgres and MySql
name: "database"
services:
  # mysql database
  mysql:
    container_name: mysql
    # set the image version, currently I need to use mysql 8.2
    image: mysql:8.2
    # this will always restart the service unless
    # the container is stopped
    restart: unless-stopped
    ports:
      - "3306:3306"
    # set mysql environment
    # this will use as container environment variable, some of the following variable
    # are set on .env file
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # persistent volume for storing mysql data
    volumes:
      - "./../../storage/mysql:/var/lib/mysql"